### PR TITLE
First try at setting up differential updates

### PR DESCRIPTION
**Pull request by gorhill**

### CODE REVIEW

**Comment by gorhill** [comment]
Now you can go to: https://github.com/dimisa-RUAdList/RUAdListCDN/actions/workflows/main.yml

Then select "Update CDN assets"

image

Then select "Run workflow"

image

Then let's see what happens

**Comment by gorhill** [comment]
Errr actually never mind, I can test that all on my side since I have a fork...

**Comment by dimisa-RUAdList** [comment]
I've already done everything.

**Comment by gorhill** [comment]
I had stuff to fix.

From now on, every 5 hours a new version of the list will be created from latest changes, and a new patch should be created along with it. uBO will use that patch to update the list client-side every ~5 hours.

**Comment by gorhill** [comment]
If you want to add more diff-updatable lists, this can be done.

**Comment by dimisa-RUAdList** [comment]
I think about this. I have two more popular filters, BitBlock and Counters, but the first of them is combined, and is collected on `easylist-downloads.adblockplus.org`. For them to work in the diff-version, I will need to separate the links for subscriptions, and here users can make mistakes by connecting them to AdBlock Plus, or vice versa, by connecting regular versions of filters to uBlock Origin. I really like the idea, but I don’t yet understand how to implement it without harming users.

**Comment by gorhill** [comment]
Well lists here I thought they were implicitly for uBO, so ABP users are not going to use these. I didn't put uBO in the name, maybe I should have.

**Comment by dimisa-RUAdList** [comment]
Obviously I should describe the problem in more detail. I'll do it later (tomorrow).

**Comment by dimisa-RUAdList** [comment]
So, I will describe the problems that I fear when creating diff-versions of BitBlock and Counters.

Both of these filters cannot be activated in the extension interface; you must either subscribe to them or import their addresses manually. And when a user of the same Adblock Plus tries to connect a diff-version of the filter, nothing will work for him and in the end he will abandon it altogether.

By the way, it was precisely because of Adblock Plus users that I was forced to use the `#include` directive in the RU AdList filter rather than `%include`. Users thought that by connecting the RU AdList filter for uBlock Origin, they would get a more effective blocking. But when AdBlock Plus encounters invalid rules that are only compatible with uBlock Origin, it completely disables all rules on the domain, and as a result I received a huge number of complaints.

As for uBlock Origin users, those who have BitBlock and Counters connected will need to first delete the old versions, and only then import the diff-versions. In the case of RU AdList, the switch will happen seamlessly, they won’t even know about it, whereas with imported filters a mass transition to diff-versions may not happen at all.

By the way, I wanted to ask why the header of the standard RU AdList filter always displays `! Last modified: %timestamp%`?

**Comment by gorhill** [comment]
> when a user of the same Adblock Plus tries to connect a diff-version of the filter, nothing will work for him

Why would it not work?

**Comment by gorhill** [comment]
> why the header of the standard RU AdList filter always displays ! Last modified: %timestamp%?

Because it's the way the list is published in your repo. It's for you to publish a version with the timestamp filled in. At uAssets, this is done by a workflow, and the patched lists with proper timestamp are committed in a different branch, you probably would need to do something similar. But anyway, probably not needed at this point since the official one will become the one here once it's confirmed all work as intended.

**Comment by dimisa-RUAdList** [comment]
<details>
<summary>Screenshot(s)</summary>

Ru diff

</details>

**Comment by gorhill** [comment]
Must be because of the missing `[Adblock Plus 2.0]`, we can add this.

**Comment by dimisa-RUAdList** [comment]
This only makes sense to ensure that the filter will not be rejected. Then will need to remove compatibility so that the rules specific to uBlock Origin do not break the work of classic rules in AdBlock plus.

**Comment by gorhill** [comment]
Surely you have instructions somewhere about how to subscribe to lists according to which blocker is in use? Just pointing out to uBO users to use the lists here, and telling ABP/AB users to follow another link should be fine. The advantage of having your other lists here is that for uBO they would be using significantly less bandwidth while being updated multiple times per day.

**Comment by gorhill** [comment]
Well, anyway, finally first patch generated: https://github.com/dimisa-RUAdList/RUAdListCDN/blob/main/patches/2023.11.8.1378.patch

So I will be replacing the current `RUS-0` URLs soon, I will just wait for the second patch in 5 hour to ensure all is working as expected.

**Comment by dimisa-RUAdList** [comment]
Bingo! The work flow worked and the update occurred. And yes, now the filter is included in Adblock Plus. Compatibility can be removed.

Do I understand correctly that the diff versions will work even if they are connected in earlier versions of uBlock Origin?

**Comment by gorhill** [comment]
> Compatibility can be removed.

Ok so you want the `[Adblock Plus 2.0]` removed? If so, let's just replace it with `[uBlock Origin 1.0]` -- uBO does nothing with it but just for the sake of whoever looks at the list.

**Comment by dimisa-RUAdList** [comment]
I agree.

**Comment by dimisa-RUAdList** [comment]
Now, if I change a rule, the user can pull it out when updating within 15 minutes after the commit. How long will the user have to wait in this case when using the diff-version of the filter?

**Comment by gorhill** [comment]
ruadlist.ubo.min.txt is updated every ~5 hours.

If they force a manual update of the list, this fetches `https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt`, which is more up to date, but not diff-updatable. The diff-updater will start to kick only after it fetches the list from `https://raw.githubusercontent.com/dimisa-RUAdList/RUAdListCDN/main/lists/ruadlist.ubo.min.txt`. From any other location, the `! Expires:` directive will tell when to auto update next.

**Comment by dimisa-RUAdList** [comment]
Great! Then I propose returning to the idea of ​​creating diff-versions of BitBlock and Counters.

**Comment by gorhill** [comment]
For RUAdList this was easy since all components are in `RuAdList-uBO.txt`. Where are the components for BitBlock and Counters, i.e. how are they assembled?

**Comment by dimisa-RUAdList** [comment]
Counters - one-page filter: `https://github.com/easylist/ruadlist/blob/master/cntblock.txt`

BitBlock is assembled on `easylist-downloads.adblockplus.org` using this file: `https://github.com/easylist/ruadlist/blob/master/bitblock.txt`

**Comment by dimisa-RUAdList** [comment]
Update error again: https://github.com/dimisa-RUAdList/RUAdListCDN/actions/runs/6817533333

**Comment by gorhill** [comment]
It's because it's trying to clone a version which didn't exist, and it doesn't exist because it failed to be created due to the missing write permission. I've added a check in the script to detect non-existing version.

**Comment by dimisa-RUAdList** [comment]
It looks like everything is working as it should now.

**Comment by dimisa-RUAdList** [comment]
If I update the filter manually, I still see in the header: `! Last modified: %timestamp%`. Do I need to fix something on my side, or should I just wait?

**Comment by gorhill** [comment]
If you update manually, it fetches the non-diff-updatable lists as before. Auto-upate has to kick in for uBO to fetch from one of the CDNs which hosts the diff-updatable lists. At the moment I am waiting for RUAdList to auto-update on my side to confirm it works.

**Comment by gorhill** [comment]
Finally the auto updater pulled the diff-updatable version of the list, now I will wait to see how it goes for the next couple of diff-updates.

**Comment by dimisa-RUAdList** [comment]
Error again: https://github.com/dimisa-RUAdList/RUAdListCDN/actions/runs/6853435608

**Comment by gorhill** [comment]
Yes, forgot to push the new file to repo. Fixed a few minutes ago.

**Comment by gorhill** [comment]
I am still investigating an issue with diff-patching ruadlist, it fails with `baddiff`.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
Errors appeared again: https://github.com/dimisa-RUAdList/RUAdListCDN/actions/runs/8567153589

**Comment by gorhill** [comment]
GitHub probably had issues, the following workflow went fine.

**Pull request merged**
